### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aNyMoRe0505** [aNyMoRe0505/official-site#1]
- [x] About 工作經歷展開

- [x] About 學歷

- [x] Practice => Slide

- [x] Practice => Index Tool (for Blog)

- [x] Medium 文章搬遷

- [x] 待補Blog：usePreviousValue concept

- [x] 待補Blog：React state update on an unmounted component

- [x] 跨環境style問題

- [x] dark mode

- [x] notification sample with saga
